# This file was auto generated by Styx.
# Do not edit this file directly.

from styxdefs import *
import pathlib
import typing

EXTRACTTXT_METADATA = Metadata(
    id="5cd990a3d02c22e3a4e1e068ed42a20e350d83dc",
    name="extracttxt",
    container_image_type="docker",
    container_image_index="index.docker.io",
    container_image_tag="mcin/docker-fsl:latest",
)


class ExtracttxtOutputs(typing.NamedTuple):
    """
    Output object returned when calling `extracttxt(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""
    output_file: OutputPathType
    """Extracted text output file"""


def extracttxt(
    search_word: str,
    file: InputPathType,
    num_trailing_lines: float | int | None = 0,
    relative_start: float | int | None = 0,
    runner: Runner | None = None,
) -> ExtracttxtOutputs:
    """
    extracttxt by Oxford Centre for Functional MRI of the Brain (FMRIB).
    
    Extracts text from a file based on a search word.
    
    Args:
        search_word: The word to search for in the file.
        file: Path to the file where text is to be extracted.
        num_trailing_lines: Number of trailing lines to include after the\
            search word.
        relative_start: Relative start position to begin the search.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `ExtracttxtOutputs`).
    """
    runner = runner or get_global_runner()
    execution = runner.start_execution(EXTRACTTXT_METADATA)
    cargs = []
    cargs.append("/usr/local/fsl/bin/extracttxt")
    cargs.append(search_word)
    cargs.append(execution.input_file(file))
    if num_trailing_lines is not None:
        cargs.append(str(num_trailing_lines))
    if relative_start is not None:
        cargs.append(str(relative_start))
    ret = ExtracttxtOutputs(
        root=execution.output_file("."),
        output_file=execution.output_file(f"output.txt"),
    )
    execution.run(cargs)
    return ret


__all__ = [
    "EXTRACTTXT_METADATA",
    "ExtracttxtOutputs",
    "extracttxt",
]
