# This file was auto generated by Styx.
# Do not edit this file directly.

from styxdefs import *
import pathlib
import typing

APQC_MAKE_HTML_METADATA = Metadata(
    id="8435db2448649c8d9b893cadcc35d2450fae07f7",
    name="apqc_make_html",
)


class ApqcMakeHtmlOutputs(typing.NamedTuple):
    """
    Output object returned when calling `apqc_make_html(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""


def apqc_make_html(
    qc_dir: str,
    runner: Runner | None = None,
) -> ApqcMakeHtmlOutputs:
    """
    apqc_make_html.
    
    Tool to generate HTML reports.
    
    Args:
        qc_dir: Directory where QC files will be saved.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `ApqcMakeHtmlOutputs`).
    """
    runner = runner or get_global_runner()
    execution = runner.start_execution(APQC_MAKE_HTML_METADATA)
    cargs = []
    cargs.append("apqc_make_html.py")
    cargs.append("-qc_dir")
    cargs.append(qc_dir)
    ret = ApqcMakeHtmlOutputs(
        root=execution.output_file("."),
    )
    execution.run(cargs)
    return ret


__all__ = [
    "APQC_MAKE_HTML_METADATA",
    "ApqcMakeHtmlOutputs",
    "apqc_make_html",
]
