name: Validate JSON
on:
  push:
      branches:
      - main
      tags:
      - '*'
  pull_request:


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: GrantBirki/json-yaml-validate@v2.7.1
        with:
          mode: warn
          base_dir: descriptors
          json_schema: schemas/descriptor.schema.json
          json_schema_version: draft-07
          ajv_strict_mode: false
          use_gitignore: false
          json_exclude_regex: ''