name: Validate & Spell-Check
on:
  push:
      branches:
      - main
      tags:
      - '*'
  pull_request:


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: GrantBirki/json-yaml-validate@v3.2.1
        with:
          mode: warn
          base_dir: descriptors
          json_schema: schemas/descriptor.schema.json
          json_schema_version: draft-07
          ajv_strict_mode: false
          use_gitignore: false
          json_exclude_regex: ''
      - name: Spell-Check JSON
        uses: codespell-project/actions-codespell@v2
        with:
            only_warn: 1
            ignore_words_file: .codespellignore
            path: descriptors